format = """
$username\
[@](fg:color6)$hostname\
$directory\
$git_branch\
$git_status\
$time\
$fill\
$cmd_duration\
$golang\
$nodejs\
$python\
$c\
$cpp\
$docker_context\
$line_break\
$character\
"""

palette = "catppuccin_mocha"

[fill]
symbol = ' '

[character]
success_symbol = '[](fg:color4)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'

[cmd_duration]
min_time = 500
format = 'takes (bold yellow)[$duration](bold yellow)'

[memory_usage]
disabled = false
threshold = -1
symbol = ''
style = 'bold dimmed green'

[battery]
disabled = false
format = " [$symbol$percentage ]($style)"
full_symbol = "󱊢 "
discharging_symbol = "󱊢 "
charging_symbol = "󰂄 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "

[[battery.display]]
threshold = 100
style = "fg:color3"

[username]
show_always = true
style_user = "fg:color1"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "fg:color5"
format = "[$hostname]($style)"
disabled = false
aliases = { "arch" = "arch" }

[directory]
style = "fg:color6"
format = " [$path]($style)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " 󰘬"
style = "fg:color3"
format = "[$symbol $branch]($style)"

[git_status]
style = "fg:color3"
format = '([\($all_status$ahead_behind\)]($style))'

[golang]
symbol = " "
style = "fg:color6"
format = "[ $symbol($version)]($style)"

[nodejs]
symbol = ""
style = "fg:color2"
format = "[ $symbol ($version)]($style)"

[python]
symbol = ""
style = "fg:color6"
format = "[ $symbol ($version)]($style)"

[c]
symbol = " "
style = "bg:color5"
format = "[ $symbol ($version)]($style)"

[cpp]
symbol = " "
style = "fg:color5"
format = "[ $symbol ($version)]($style)"

[docker_context]
symbol = ""
style = "fg:color4"
format = "[ $symbol $context]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:color7"
format = " [$time]($style)"

[line_break]
disabled = false

[os]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[palettes.catppuccin_mocha]
fg = "#CDD6F4"
bg = "#1E1E2E"
color0 = "45475A"
color1 = "#F38BA8"
color2 = "#A6E3A1"
color3 = "#F9E2AF"
color4 = "#89B4FA"
color5 = "#F5C2E7"
color6 = "#94E2D5"
color7 = "#BAC2DE"

[palettes.tokyonight]
bg = "#1a1b26"
fg = "#c0caf5"
color0 = "#15161e"
color1 = "#f7768e"
color2 = "#9ece6a"
color3 = "#e0af68"
color4 = "#7aa2f7"
color5 = "#bb9af7"
color6 = "#7dcfff"
color7 = "#a9b1d6"
