# =============================================================================
# HYPRLAND CONFIG
# =============================================================================

### CONFIG
source = $HOME/.config/hypr/conf.d/monitors.conf
source = $HOME/.config/hypr/conf.d/programs.conf
source = $HOME/.config/hypr/conf.d/bindings.conf
source = $HOME/.config/hypr/conf.d/autostart.conf
source = $HOME/.config/hypr/conf.d/envs.conf
source = $HOME/.config/hypr/conf.d/permissions.conf
source = $HOME/.config/hypr/conf.d/looknfeel.conf
source = $HOME/.config/hypr/conf.d/windows.conf
source = $HOME/.config/hypr/conf.d/input.conf

### APPS
source = $HOME/.config/hypr/apps/scratchpad-term.conf
