# =============================================================================
# KEY BINDS
# =============================================================================

$mainMod = SUPER

# --- Personals ---
bind = $mainMod, C, sendshortcut, CTRL, Insert, activewindow
bind = $mainMod, V, sendshortcut, SHIFT, Insert, activewindow
bind = $mainMod, X, sendshortcut, CTRL, X, activewindow
bind = $mainMod, A, sendshortcut, CTRL, A, activewindow
bind = $mainMod, Z, sendshortcut, CTRL, Z, activewindow

# --- Apps & Essentials ---
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod SHIFT, B, exec, $browser --private
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod CTRL, SPACE, exec, toggle-waybar

bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, P, pseudo,
bind = $mainMod CTRL, J, togglesplit,
bind = $mainMod, O, togglefloating,

# --- Focus Move ---
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# --- Swap Window ---
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# --- Workspaces Switch ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# --- Move Window to Workspace ---
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# --- Scratchpad ---
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
bind = $mainMod SHIFT, RETURN, exec, $scratchpad_term

# --- Resize Submap ---
bind = $mainMod, R, submap, resize
submap = resize
    binde = , l, resizeactive, 5 0
    binde = , h, resizeactive, -5 0
    binde = , k, resizeactive, 0 -5
    binde = , j, resizeactive, 0 5
    bind = , escape, submap, reset
submap = reset

# --- Screen & Color Utilities ---
# bind = $mainMod SHIFT, P, exec, grim -g "$(slurp)" - | wl-copy
bind = , PRINT, exec, cmd-screenshot
bind = SUPER, PRINT, exec, pkill hyprpicker || hyprpicker -a

# --- Mouse Bindings ---
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# --- Media & System Control ---
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl  = , XF86AudioPlay, exec, playerctl play-pause
bindl  = , XF86AudioNext, exec, playerctl next
bindl  = , XF86AudioPrev, exec, playerctl previous
