# =============================================================================
# LOOK AND FEEL
# =============================================================================

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(89b4fa77) rgba(b4befeff) 60deg
    col.inactive_border = rgba(313244aa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

source = $HOME/.config/hypr/conf.d/decoration.conf
source = $HOME/.config/hypr/conf.d/animations.conf

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    # --- Performance & Cleanliness ---
    vfr = true
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    # --- Aesthetic ---
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    background_color = rgb(000000)
}
