###################
### MY PROGRAMS ###
###################

$terminal = uwsm-app -- xdg-terminal-exec
$fileManager = dolphin
$menu = wofi
$browser = launch-browser

# Personals
$scratchpad_term = uwsm-app -- env NO_TMUX=1 kitty --class scratchpad_term
