return {}
-- return {
--     {
--         "catppuccin/nvim",
--         name = "catppuccin",
--         config = function()
--             require("catppuccin").setup({
--                 flavour = "auto", -- latte, frappe, macchiato, mocha
--                 background = {
--                     light = "latte",
--                     dark = "mocha",
--                 },
--                 transparent_background = true,
--                 float = {
--                     transparent = true,
--                     solid = true,
--                 },
--                 integrations = {
--                     bufferline = true,
--                 },
--             })
--             vim.cmd.colorscheme("catppuccin")
--         end,
--     },
--     {
--         "akinsho/bufferline.nvim",
--         opts = function(_, opts)
--             local catppuccin = require("catppuccin.groups.integrations.bufferline")
--             if catppuccin and catppuccin.get then
--                 opts.highlights = catppuccin.get()
--             end
--         end,
--     },
-- }
